name = "face-score"
compatibility_date = "2024-01-01"

[[unsafe.bindings]]
name = "AI"
binding = "AI"
type = "ai"

[[d1_databases]]
binding = "FACE_SCORE_DB"
database_name = "face-score-db"
database_id = "f081ceb00df741d29d5a82500c2adaed"

[[r2_buckets]]
binding = "FACE_IMAGES"
bucket_name = "face-score-images"
preview_bucket_name = "face-score-images-preview"